    #############################################################################
    #############################################################################
    ######### Managed by Terraform, not safe to change ##########################
    #############################################################################
    #############################################################################
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  values:
    server:
      extraEnvironmentVars:
        VAULT_SEAL_TYPE: awskms
        VAULT_AWSKMS_SEAL_KEY_ID: 3c3e3d30-a91c-4819-8e34-390ec0da9958
        AWS_REGION: eu-west-1

      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::492737776546:role/akoh-vault
    ui:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: vault.akoh.local
