    #############################################################################
    #############################################################################
    ######### Managed by Terraform, not safe to change ##########################
    #############################################################################
    #############################################################################
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  values:
    server:
      extraEnvironmentVars:
        VAULT_SEAL_TYPE: awskms
        VAULT_AWSKMS_SEAL_KEY_ID: af497662-0565-4075-9ac5-6e484e214b5f
        AWS_REGION: eu-west-2

      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::492737776546:role/akoh-vault
    ui:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: vault.akoh.local
