apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
  # namespace: cert-manager
spec:
  vault:
    server: https://vault.${resource_prefix}.local
    caBundle: ${ca_base64}
